In [1]:
import pandas as pd 
import numpy as np

In [32]:
df = pd.read_csv("HDI_Index.csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

df.to_csv("HDI_Index.csv")

In [33]:
df = pd.read_csv("AVG_Healthcare_Expenditure.csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

df.to_csv("AVG_Healthcare_Expenditure.csv")

### No of Doctors

In [34]:
df = pd.read_csv("No_of_Doctors_per_10,000.csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1970, 2023)],
                      var_name='Year', value_name='Doctors_Per_10000')

melted_data = melted_data.dropna(subset=['Doctors_Per_10000'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['Doctors_Per_10000'] != 'no data']

df_cleaned['Doctors_Per_10000'] = pd.to_numeric(df_cleaned['Doctors_Per_10000'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('Doctors_Per_10000_Final.csv', index=False)

df_cleaned.head()

                Country  Year  Doctors_Per_10000
0           Afghanistan  1970              0.065
1                Angola  1970              0.116
2               Albania  1970              0.739
3  United Arab Emirates  1970              0.909
4             Argentina  1970              1.892

### Poverty Data

In [35]:
df = pd.read_csv("Poverty Data (People earning less than $2.5).csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1980, 2023)],
                      var_name='Year', value_name='Poverty_Percentage')

melted_data = melted_data.dropna(subset=['Poverty_Percentage'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['Poverty_Percentage'] != 'no data']

df_cleaned['Poverty_Percentage'] = pd.to_numeric(df_cleaned['Poverty_Percentage'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('Poverty_Percentage_Final.csv', index=False)

df_cleaned.head()

          Country  Year  Poverty_Percentage
0       Argentina  1980                 0.3
1        Colombia  1980                20.8
2           Spain  1980                 0.5
3  United Kingdom  1980                 0.0
4           Italy  1980                 0.2

### Access to Power

In [36]:
df = pd.read_csv("Access to Electricity 1990-2022.csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1990, 2023)],
                      var_name='Year', value_name='Access_to_Electricity')

melted_data = melted_data.dropna(subset=['Access_to_Electricity'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['Access_to_Electricity'] != 'no data']

df_cleaned['Access_to_Electricity'] = pd.to_numeric(df_cleaned['Access_to_Electricity'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('Access_to_Electricity_Final.csv', index=False)

df_cleaned.head()

                Country  Year  Access_to_Electricity
0                 Aruba  1990               100.0000
1               Albania  1990               100.0000
2               Andorra  1990               100.0000
3  United Arab Emirates  1990               100.0000
4             Argentina  1990                92.1548

#### Life Expacatancy at Birth

In [37]:
df = pd.read_csv("LE_at_B.csv")

df['Country'] = df['Country'].replace("Cote d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")
df['Country'] = df['Country'].replace("Czechia", "Czech Republic")
df['Country'] = df['Country'].replace("Hong Kong SAR, China", "Hong Kong")
df['Country'] = df['Country'].replace("Korea, Rep.", "South Korea")
df['Country'] = df['Country'].replace("Turkiye", "Turkey")
df['Country'] = df['Country'].replace("Russian Federation", "Russia")
df['Country'] = df['Country'].replace("Slovak Republic", "Slovakia")
df['Country'] = df['Country'].replace("Macao SAR, China", "Taiwan")
df['Country'] = df['Country'].replace("Egypt, Arab Rep.", "Egypt")
df['Country'] = df['Country'].replace("Iran, Islamic Rep.", "Iran")
df['Country'] = df['Country'].replace("Viet Nam", "Vietnam")
df['Country'] = df['Country'].replace("Venezuela, RB", "Venezuela")
df['Country'] = df['Country'].replace("Bosnia and Herzegovina", "Bosnia And Herzegovina")
df['Country'] = df['Country'].replace("Syrian Arab Republic", "Syria")
df['Country'] = df['Country'].replace("TÃ¯Â¿Â½rkiye", "Turkey")
df['Country'] = df['Country'].replace("United Kingdom of Great Britain and Northern Ireland", "United Kingdom")
df['Country'] = df['Country'].replace("Republic of Korea", "South Korea")
df['Country'] = df['Country'].replace("United States of America", "United States")
df['Country'] = df['Country'].replace("Netherlands (Kingdom of the)", "Netherlands")
df['Country'] = df['Country'].replace("Iran (Islamic Republic of)", "Iran")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1970, 2023)],
                      var_name='Year', value_name='LE_at_birth')

melted_data = melted_data.dropna(subset=['LE_at_birth'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['LE_at_birth'] != 'no data']

df_cleaned['LE_at_birth'] = pd.to_numeric(df_cleaned['LE_at_birth'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('LE_at_birth_Final.csv', index=False)

df_cleaned.head()

                       Country  Year  LE_at_birth
0                        Aruba  1970    67.583000
1  Africa Eastern and Southern  1970    46.718485
2                  Afghanistan  1970    37.418000
3   Africa Western and Central  1970    41.034761
4                       Angola  1970    40.190000

In [38]:
doctors_per_10000 = pd.read_csv('Doctors_Per_10000_Final.csv')
access_to_electricity = pd.read_csv('Access_to_Electricity_Final.csv')
healthcare_data = pd.read_csv('All_countries_healthcare_data.csv')
avg_healthcare_expenditure = pd.read_csv('AVG_Healthcare_Expenditure.csv', encoding='latin-1')
crime_rate_data = pd.read_csv('crimerate_data_all_countries.csv')
hdi_index = pd.read_csv('HDI_Index.csv')
le_at_birth = pd.read_csv('LE_at_birth_Final.csv')

In [39]:
merged_df = pd.merge(le_at_birth, doctors_per_10000, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, access_to_electricity, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, hdi_index, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, avg_healthcare_expenditure, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, healthcare_data, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, crime_rate_data, on=['Year', 'Country'], how='outer')

merged_df.to_csv('Quality_of_Life_final.csv', index=False)